server:
  error:
    whitelabel:
      enabled: false

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

  # PostgreSql
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: chat
    password: chat
  jpa:
    generate-ddl: false
    show-sql: true

  # Cassandra
  cassandra:
    local-datacenter: datacenter1
    keyspace-name: chat
    username: cassandra
    password: cassandra
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s

  # Redis
redis:
  host: localhost
  port: 6379